This is a new york times website cloned by Uchenna Anya and Henoks Mossissa built with HTML5 and CSS3, not forgetting other development technologies like linters, webhint and stylelint.
uchennaanya/newyork-times pull request #1
Opened 2020-09-24 20:56 UTC by uchennaanya

This is a new york times website cloned by Uchenna Anya and Henoks Mossissa built with HTML5 and CSS3, not forgetting other development technologies like linter, webhint, and stylelint.

2020-09-25 11:25 UTC, arslanbisharat requested changes
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet.😟 You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

- [ ] Remove conflict of files

- [ ] Please create only one PR that you use for code review request and submit that one.

- [ ] Please remove all linter errors

- [ ] Add node_modules in gitigonre file.

- [ ] Your Live link is not updated. Please update it.

- [ ] Your PR is not descriptive. Please add more details

- [ ] The whole page is overlapped. Please fix this. 
![chrome-capture (22)](https://user-images.githubusercontent.com/58504655/94261653-a68b5280-ff4b-11ea-8807-4a3eff547b19.jpg)

- [ ] You have a number of validation errors. Please resolve those too.
 

**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-09-28 13:28 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-28 13:33 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] Remove `!important `from css file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)

- [ ] Remove conflict message from .gitignore file 
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-28 13:33 UTC, umairarshadbutt commented on assets/css/style.css
> +  background-color: transparent !important;
Remove` !important`

2020-09-28 13:33 UTC, umairarshadbutt commented on .gitignore
> +>>>>>>> a98662c6d022f392b0a8d7e1422c35e673489652
Please remove conflict messages

2020-09-28 14:01 UTC, arslanbisharat approved these changes
### Congratulations APPROVED :clap:
Hello, I can see you worked really hard on this project. and I'm very happy to approve this project with the latest changes you made in this project. :satisfied:
_The clone shows a good understanding and usage of HTML CSS💯_

- The cloned page is rendering as it should and meets all the project specifications.
-  CSS is clean.
-  The markup as well has no errors nor warnings to show. Good job with that.
-  The repo has followed all the guidelines there are to follow.
-  All the required tasks have been fulfilled in this project.
-  Congratulations on the splendid job👍
Now you can merge the branches and move forward with your curriculum. 🎆 

[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 

I am very excited to see your next project.

**Happy Coding**:smiley:
------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) slack: @arslanbisharat

2021-04-07 07:55 UTC, merged